[jinja2:suite.rc]
BUILD_MODE="spack"
CRUN_LEN=6
CYCLE_INT_HR=24
INITIAL_CYCLE_POINT="20220226T0000Z"
FINAL_CYCLE_POINT="20220227T0000Z"
FREE_RUN=true
HK_RUN=true,false
MAKE_FRAMES=false
NCI_ERA5GRIB=true
NCI_HRES_ECCB="era5land"
NCI_STORAGE="scratch/$PROJECT"
NCI_STORAGE_TOP_DIR="unset"
NCI_STORAGE_TYPE='gdata'
SITE="nci-gadi"
SPACK_VERSION="2025.08.000"
dm_ec_cb_freq=3600
dm_ec_ic_lbc_dir="/scratch/$PROJECT/$USER/EC_GRIB_PARALLEL"
dm_ec_lam_ancil_dir="/scratch/$PROJECT/$USER/cylc-run/rCM3-test-UM-ancil/share/data/ancils/Lismore/era5"
dm_nregns=1
rg01_name="Test_Ocean"
rg01_nreslns=1