[jinja2:suite.rc]
# Generic suite options
BUILD_MODE="spack"
CRUN_LEN=6
CYCLE_INT_HR=24
INITIAL_CYCLE_POINT="20220226T0000Z"
FINAL_CYCLE_POINT="20220227T0000Z"
CASE_STUDIES=false
FREE_RUN=true
HK_RUN=true,false
MAKE_FRAMES=false
NCI_ERA5GRIB=true
NCI_HRES_ECCB="era5land"
NCI_STORAGE="scratch/$PROJECT"
NCI_STORAGE_TOP_DIR="unset"
NCI_STORAGE_TYPE='gdata'
SITE="nci-gadi"
SPACK_VERSION="2025.08.000"
WALL_CLOCK_LIMIT=1800

# Defining the 'driving model' (dm) i.e. where are your
# initial and boundary conditions coming from?
# Point to the ancilliaries which define the driving model
# domain
dm_nregns=1
dm_name="ec"
dm_ec_cb_freq=3600
dm_ec_ic_lbc_dir="/scratch/$PROJECT/$USER/EC_GRIB_PARALLEL"
dm_ec_lam_ancil_dir="/scratch/$PROJECT/$USER/cylc-run/rCM3-test-UM-ancil/share/data/ancils/Lismore/era5"
dm_ec_mode="an"

# Define your UM foreast region (rg01)
# Define the number of resolutions or nests (rs01)
# Point to the ancilliaries which define the UM resolution
rg01_name="Test_Ocean"
rg01_nreslns=1
rg01_rs01_std_model="custom"
rg01_rs01_name="test"
rg01_rs01_nmods=1
rg01_rs01_vargrid="fixed"
rg01_rs01_zon_avg_ozone=false
rg01_rs01_3D_ancils=true
rg01_rs01_alb_anc=false
rg01_rs01_ancil_dir="/scratch/$PROJECT/$USER/cylc-run/rCM3-test-UM-ancil/share/data/ancils/Lismore/d1100"
rg01_rs01_downscale_ukv=false
rg01_rs01_kscale=false
rg01_rs01_lai_anc=true
rg01_rs01_levset="L70_80km"
rg01_rs01_m01_arch=false,false,false
rg01_rs01_m01_config="GAL9"
rg01_rs01_m01_dt=120
rg01_rs01_m01_lbc_freq=3600,1800
rg01_rs01_m01_moruses=false
rg01_rs01_m01_name="GAL9"
rg01_rs01_m01_nproc=2,1
rg01_rs01_m01_progdust=false,false
rg01_rs01_m01_raddt=1800,600
rg01_rs01_m01_simim=false
rg01_rs01_m01_stashpack=true,false,false,false