meta=um-createbc/vn13.5

[command]
default=um-createbc.exe input.nl

[env]
DR_HOOK=false
!!DR_HOOK_CATCH_SIGNALS=0
!!DR_HOOK_IGNORE_SIGNALS=0
!!DR_HOOK_OPT=self,wallprof
!!DR_HOOK_PROFILE=$CYLC_TASK_WORK_DIR/drhook.prof.%d
!!DR_HOOK_PROFILE_LIMIT=-10.0
!!DR_HOOK_PROFILE_PROC=-1
OMP_NUM_THREADS=$OMP_NUM_THREADS
OMP_STACKSIZE=2G
VN=13.5

[file:input.nl]
source=namelist:lbc_grid

[namelist:lbc_grid]
dlat=$DEL_Y
dlong=$DEL_X
end_time=$END_DATE
!!frames_packing_option=-1
halo_lat=7
halo_long=7
!!horizontal_grid_file='$UM_INSTALL_DIR/vn$VN/ctldata/horiz/horizgr_seukv_um_eg'
horizontal_interpolation_method=2
input_data=$INPUT_FILES
nlat=$NPTS_Y
nlong=$NPTS_X
num_levels=$NLEVS
num_reserved_headers=$NUM_HEADERS
output_filename='$OUTPUT_FILE'
output_grid_stagger=6
pole_lat=$POLE_LAT
pole_long=$POLE_LON
q_min=2.500e-6
rim_width=9
start_lat=$FIRST_LAT
start_long=$FIRST_LON
start_time=$START_DATE
stash_codes=$STASH_CODES
stashmaster_path='$ROSE_DATA/etc/um_STASHmaster'
time_interval=$LBC_FREQ
variable_resolution=.false.
vertical_interpolation_method=1
vertical_levels_file='$VERT_LEV'
write_header_only_once=.false.
