[env=ERA5LAND]
type=python_boolean
description=Use values from era5land over land cells

[env=POLAR]
type=python_boolean
description=Output all longitudes, e.g. when working close to the poles or over the prime meridian
