[namelist:items(6ecde8dd)]
ancilfilename='$UM_ANCIL_MURK_DIR/$UM_ANCIL_MURK_FILE'
domain=1
interval=1
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
period=3
source=2
stash_req=57
update_anc=.true.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:run_murk]
l_murk=.true.
l_murk_advect=.true.
l_murk_source=.true.
l_murk_vis=.false.
m0_murk_scale=1.0
murk_source_scale=1.0

[namelist:run_precip]
l_autoconv_murk=.false.
