[!namelist:items(47868183)]
!ancilfilename='$UM_ANCIL_GENLAND_DIR/$UM_ANCIL_GENLAND_FILE'
!domain=1
!l_ignore_ancil_grid_check=.false.
!source=2
!stash_req=243
!update_anc=.false.

[namelist:items(4ec0b501)]
ancilfilename='$UM_ANCIL_GENSEA_DIR/$UM_ANCIL_GENSEA_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=96
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[!namelist:items(8e0b5d58)]

[!namelist:items(d783f0fa)]
!ancilfilename='$UM_ANCIL_GENLAND_DIR/$UM_ANCIL_GENLAND_FILE'
!domain=1
!!interval=1
!l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
!!period=1
!source=2
!stash_req=243
!update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[!namelist:items(e7100f44)]

[namelist:items(f0c6ba27)]
ancilfilename='$UM_ANCIL_GENLAND_DIR/$UM_ANCIL_GENLAND_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=244,245
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:jules_hydrology]
l_var_rainfrac=.true.
nfita=30

[namelist:jules_nvegparm]
albsnf_nvgl_io=0.05,0.06,0.03,0.75

[namelist:jules_pftparm]
!!albsnf_max_io=1.43000e-1,8.80000e-2,1.92000e-1,1.59000e-1,1.15000e-1
alniru_io=0.75,0.65,0.95,0.95,0.87
alparu_io=0.15,0.11,0.25,0.25,0.25
!!ci_st_io=33.46,33.46,34.26,29.98,34.26
!!gpp_st_io=1.29E-07,2.58E-08,2.07E-07,3.42E-07,1.68E-007
lai_alb_lim_io=5*0.005
omegau_io=0.23,0.23,0.35,0.35,0.35

[namelist:jules_radiation]
i_sea_alb_method=3
l_embedded_snow=.true.
l_mask_snow_orog=.true.
l_sea_alb_var_chl=.true.
l_spec_alb_bs=.true.
l_spec_albedo=.true.

[namelist:jules_sea_seaice]
a_chrn_coare=0.0016
b_chrn_coare=-0.0035
beta_floe=1.0
ce_floe=0.222
!!charnock=0.0180
d_floe_max=300.0
d_floe_min=8.0
h_freeboard_max=0.534
h_freeboard_min=0.286
iseasurfalg=3
kappai_snow=0.256
l_10m_neut=.false.
l_iceformdrag_lupkes=.true.
l_stability_lupkes=.true.
ss_floe=0.5
u10_max_coare=22.0
u10_min_coare=0.0
!!z0h_z0m_miz=0.200
!!z0miz=1.00000e-1
z0sice=5.00000e-4

[namelist:jules_snow]
a_snow_et=2.8e-6
b_snow_et=0.042
c_snow_et=0.046
can_clump=1.0,4.0,1.0,1.0,1.0
dzsnow=0.04,0.12,0.34
i_grain_growth_opt=1
i_relayer_opt=1
i_snow_cond_parm=1
l_et_metamorph=.true.
l_snow_infilt=.true.
l_snow_nocan_hc=.true.
l_snowdep_surf=.true.
lai_alb_lim_sn=1.0,1.0,0.1,0.1,0.1
n_lai_exposed=1.0,1.0,3.0,3.0,2.0
nsmax=3
rho_snow_et_crit=150.0
rho_snow_fresh=109.0
snow_hcon=0.1495
unload_rate_u=0.0,2.31e-06,0.0,0.0,0.0

[namelist:jules_surface]
i_modiscopt=1
l_land_ice_imp=.true.

[namelist:jules_vegetation]
l_vegcan_soilfx=.true.

[namelist:recon_science]
l_regularize_landice=.true.
snow_icefree_max=5.0e3
snow_landice_min=5.0e4

[namelist:temp_fixes]
l_fix_rcf_mlsnow_icefreemax=.true.
