[namelist:items(6264e62e)]
ancilfilename='$UM_ANCIL_ARCLDUST_DIR/$UM_ANCIL_ARCLDUST_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.true.
!!netcdf_varname=6*'unset'
!!period=1
source=2
stash_req=362,363,364,365,366,367
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:jules_pftparm]
!!dust_veg_scj_io=0.0,0.0,1.0,1.0,0.5

[namelist:run_dust]
!!dust_veg_emiss=1
!!horiz_d=0.7
i_dust=0
!!l_fix_size_dist=.true.
!!l_twobin_dust=.true.
!!pwsdiag_sfc_em=0.0
!!sm_corr=0.30
!!us_am=2.20

[namelist:run_radiation]
l_use_arcldust=.true.
