[namelist:items(256c9479)]
ancilfilename='$UM_ANCIL_SOILDUST_DIR/$UM_ANCIL_SOILDUST_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.true.
!!netcdf_varname=6*'unset'
!!period=1
source=2
stash_req=418,419,420,421,422,423,424,425,426
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0
