[env]
DATAM=$ROSE_DATAC/ec/um
DATAW=$ROSE_DATAC/ec/um
HISTORY=$ROSE_DATAC/ec/um/umgla.xhist

[!namelist:items(47868183)]

[!namelist:items(8e0b5d58)]

[!namelist:items(e7100f44)]

[namelist:jules_hydrology]
b_pdm=0.40
dz_pdm=0.50
l_pdm=.true.
l_spdmvar=.false.
l_top=.false.
!!l_wetland_unfrozen=.false.
!!nfita=20
s_pdm=0.0
!!ti_max=10.0
!!ti_wetl=1.5
!!zw_max=6.0

[namelist:jules_nvegparm]
!!albsnf_nvgl_io=0.16,0.06,0.03,0.75
!!albsnf_nvgu_io=0.20,0.15,0.80,0.75

[namelist:jules_pftparm]
!!albsnf_maxl_io=0.095,0.059,0.128,0.106,0.077
!!albsnf_maxu_io=0.215,0.132,0.288,0.239,0.173
!!alnirl_io=0.30,0.23,0.39,0.39,0.39
!!alniru_io=0.68,0.53,0.87,0.87,0.87
!!alparl_io=0.06,0.04,0.06,0.06,0.06
!!alparu_io=0.15,0.11,0.15,0.15,0.15
!!omegal_io=0.10,0.10,0.10,0.12,0.10
!!omegau_io=0.23,0.23,0.23,0.26,0.23
!!omnirl_io=0.50,0.30,0.53,0.53,0.53
!!omniru_io=0.90,0.65,0.98,0.98,0.98

[namelist:jules_radiation]
l_albedo_obs=.false.

[namelist:jules_soil_biogeochem]
!!ch4_substrate=1
!!l_ch4_interactive=.false.
!!l_ch4_tlayered=.false.

[namelist:lam_config]
delta_lat=$DELTA_LAT
delta_lon=$DELTA_LON
frstlata=$FIRST_LAT
frstlona=$FIRST_LON
polelata=$POLE_LAT
polelona=$POLE_LON

[namelist:lbc_options]
l_lateral_boundary=.false.

[namelist:model_domain]
l_cartesian=.false.
model_type=2

[namelist:nlcfiles]
astart='$ASTART'

[namelist:nlsizes]
bl_levels=$NLEVSM1
cloud_levels=$NLEVS
global_row_length=$NPTS_X
global_rows=$NPTS_Y
model_levels=$NLEVS
ozone_levels=$NLEVS
vert_lev='$VERT_LEV'

[namelist:recon_technical]
ainitial='$AINITIAL'
input_dump_type=2

[namelist:recon_science]
use_smc_stress=.false.

[namelist:run_dyn]
conserve_dry_mass=1

[namelist:run_ozone]
zon_av_ozone=.false.

[namelist:run_ukca]
tc_lbc_ukca=150*0

[namelist:temp_fixes]
l_fix_ec_gen_hgt=.true.
