[command]
default=(module use /g/data/hh5/public/modules; module load conda; nci_era5grib.py --mask $MASK --output $OUTDIR --start $START --count $COUNT --freq $FREQ --era5land $ERA5LAND --polar $POLAR)

[env]
ERA5LAND=False
POLAR=False

[file:$OUTDIR]
mode=mkdir
