[namelist:lbc_grid]
!!dlat=$DEL_Y
!!dlong=$DEL_X
horizontal_grid_file='$UMDIR/vn${VN}/ctldata/horiz/horizgr_ukv_9501025_uk_um_eg'
!!nlat=$NPTS_Y
!!nlong=$NPTS_X
rim_width=8
!!start_lat=$FIRST_LAT
!!start_long=$FIRST_LON
variable_resolution=.true.
vertical_levels_file='$ROSE_SUITE_DIR/etc/vert_levs/L90_40km'
