[namelist:nlstcall_pp(pmotc)]
file_id='pmotc'
!!filename='unset'
filename_base='$DATAM/${RUNID}a_pmotc%N'
l_reinit=.true.
packing=1
reinit_end=-1
reinit_start=0
reinit_step=168
reinit_unit=1
reserved_headers=0

[namelist:umstash_domain(diag4_1deef4d7)]
dom_name='DIAG4'
!!iest=0
!!ilevs=0
imn=0
imsk=1
!!inth=0
iopa=1
iopl=5
!!isth=0
!!iwst=0
iwt=0
!!l_spml_ts=.false.
!!levb=0
!!levlst=0
!!levt=0
plt=0
!!pslist=0
!!rlevlst=0.0
!!spml_bot=0
!!spml_ew=0
!!spml_ns=0
!!spml_top=0
!!tblim=0
!!tblimr=0.0
!!telim=0
!!tnlim=0
ts=.false.
!!tslim=0
!!tsnum=0
!!ttlim=0
!!ttlimr=0.0
!!twlim=0

[namelist:umstash_domain(plev_850_3f355c5a)]
dom_name='PLEV_850'
!!iest=0
!!ilevs=0
imn=0
imsk=1
!!inth=0
iopa=1
iopl=3
!!isth=0
!!iwst=0
iwt=0
!!l_spml_ts=.false.
!!levb=0
!!levlst=0
!!levt=0
plt=0
!!pslist=0
rlevlst=850.0
!!spml_bot=0
!!spml_ew=0
!!spml_ns=0
!!spml_top=0
!!tblim=0
!!tblimr=0.0
!!telim=0
!!tnlim=0
ts=.false.
!!tslim=0
!!tsnum=0
!!ttlim=0
!!ttlimr=0.0
!!twlim=0

[namelist:umstash_streq(00024_dc13b1a5)]
dom_name='DIAG4'
isec=0
item=24
package='TCVER'
tim_name='HR0_6_12'
use_name='TCVER'

[namelist:umstash_streq(03225_06c5ab8b)]
dom_name='DIAG4'
isec=3
item=225
package='TCVER'
tim_name='TS1'
use_name='TCVER'

[namelist:umstash_streq(03225_39ddf1e4)]
dom_name='DIAG4'
isec=3
item=225
package='TCVER'
tim_name='STD_T6HR'
use_name='TCVER'

[namelist:umstash_streq(03226_5b1dacac)]
dom_name='DIAG4'
isec=3
item=226
package='TCVER'
tim_name='STD_T6HR'
use_name='TCVER'

[namelist:umstash_streq(03226_aa123f8e)]
dom_name='DIAG4'
isec=3
item=226
package='TCVER'
tim_name='TS1'
use_name='TCVER'

[namelist:umstash_streq(15201_6eef1a94)]
dom_name='PLEV_850'
isec=15
item=201
package='TCVER'
tim_name='TS1'
use_name='TCVER'

[namelist:umstash_streq(15201_bd244779)]
dom_name='PLEV_850'
isec=15
item=201
package='TCVER'
tim_name='STD_T6HR'
use_name='TCVER'

[namelist:umstash_streq(15202_23bccb2b)]
dom_name='PLEV_850'
isec=15
item=202
package='TCVER'
tim_name='TS1'
use_name='TCVER'

[namelist:umstash_streq(15202_76857dde)]
dom_name='PLEV_850'
isec=15
item=202
package='TCVER'
tim_name='STD_T6HR'
use_name='TCVER'

[namelist:umstash_streq(16222_adf5d7cb)]
dom_name='DIAG4'
isec=16
item=222
package='TCVER'
tim_name='STD_T6HR'
use_name='TCVER'

[namelist:umstash_streq(16222_fb1e9db5)]
dom_name='DIAG4'
isec=16
item=222
package='TCVER'
tim_name='TS1'
use_name='TCVER'

[namelist:umstash_time(hr0_6_12_3c751422)]
!!iedt=0
!!iend=0
!!ifre=0
!!intv=0
!!ioff=0
iopt=2
!!isam=0
!!isdt=0
iser=0,6,12
!!istr=0
itimes=3
ityp=1
!!lts0=.false.
tim_name='HR0_6_12'
!!unt1=2
!!unt2=2
unt3=2

[namelist:umstash_time(std_t6hr_0dae46e4)]
!!iedt=0
iend=-1
ifre=6
!!intv=0
!!ioff=0
iopt=1
!!isam=0
!!isdt=0
!!iser=0
istr=6
!!itimes=0
ityp=1
!!lts0=.false.
tim_name='STD_T6HR'
!!unt1=2
!!unt2=2
unt3=2

[namelist:umstash_use(tcver_a0a59337)]
file_id='pmotc'
locn=3
!!macrotag=0
use_name='TCVER'
