[namelist:items(4a1bb15d)]
ancilfilename='$DATADIR/glu_smow.anc'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.true.
!!netcdf_varname=''
!!period=1
source=2
stash_req=9
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0
