[namelist:gen_phys_inputs]
l_mr_physics=.true.

#LFRic uses multilayer snow
[namelist:jules_snow]
dzsnow=0.04,0.12,0.34
graupel_options=2
i_grain_growth_opt=1
i_relayer_opt=1
i_snow_cond_parm=1
l_snow_nocan_hc=.true.
nsmax=3
rho_snow_fresh=170.0

[namelist:lbc_options]
rimweightsa=4*1.0,0.9,0.7,0.5,0.3,0.1,21*0.0

# we currently zero w at the start of LFRic runs
[namelist:recon_science]
w_zero_end=70
w_zero_start=1

[namelist:run_bl]
# Conservation fix
l_reset_neg_q=.false.

# https://code.metoffice.gov.uk/trac/rmed/ticket/620
[namelist:run_murk]
l_murk_vis=.false.

[namelist:run_radiation]
aparam=0.07
bparam=-0.14
# updated mixing ratios in LFRic
c113mmr=4.826e-10
c11mmr=1.110e-09
c12mmr=2.187e-09
ch4mmr=1.006e-6
co2_mmr=6.002e-4
hcfc22mmr=6.866e-10
hfc134ammr=2.536e-10
# done as standard in LFRic
l_hydrostatic_mass=.false.
# GA8 setting brought forward
l_use_liu_spec=.true.
n2ommr=4.945e-7

