[namelist:nlstcall_pp(pwspp)]
file_id='pwspp'
!!filename='unset'
filename_base='$DATAM/${RUNID}a_ppws%N'
l_reinit=.true.
packing=1
reinit_end=-1
reinit_start=0
reinit_step=12
reinit_unit=1
reserved_headers=0

[namelist:umstash_domain(diag_pws_1deef4d7)]
dom_name='DIAG_PWS'
!!iest=0
!!ilevs=0
imn=0
imsk=1
!!inth=0
iopa=1
iopl=5
!!isth=0
!!iwst=0
iwt=0
!!l_spml_ts=.false.
!!levb=0
!!levlst=0
!!levt=0
plt=0
!!pslist=0
!!rlevlst=0.0
!!spml_bot=0
!!spml_ew=0
!!spml_ns=0
!!spml_top=0
!!tblim=0
!!tblimr=0.0
!!telim=0
!!tnlim=0
ts=.false.
!!tslim=0
!!tsnum=0
!!ttlim=0
!!ttlimr=0.0
!!twlim=0

[namelist:umstash_streq(03236_72fcf527)]
dom_name='DIAG_PWS'
isec=3
item=236
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(03237_a1c49c2c)]
dom_name='DIAG_PWS'
isec=3
item=237
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20110_d59ce442)]
dom_name='DIAG_PWS'
isec=20
item=110
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20111_80b06faa)]
dom_name='DIAG_PWS'
isec=20
item=111
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20112_e26431e8)]
dom_name='DIAG_PWS'
isec=20
item=112
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20113_0a2d9ffd)]
dom_name='DIAG_PWS'
isec=20
item=113
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20114_91bb4f2b)]
dom_name='DIAG_PWS'
isec=20
item=114
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20115_367f0d4b)]
dom_name='DIAG_PWS'
isec=20
item=115
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20116_b57fe98c)]
dom_name='DIAG_PWS'
isec=20
item=116
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20117_7e62cba7)]
dom_name='DIAG_PWS'
isec=20
item=117
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_streq(20118_527c6c1b)]
dom_name='DIAG_PWS'
isec=20
item=118
package='PWS'
tim_name='T1HR_PWS'
use_name='PWSDIAGS'

[namelist:umstash_time(t1hr_pws_5af162dd)]
!!iedt=0
iend=-1
ifre=1
!!intv=0
!!ioff=0
iopt=1
!!isam=0
!!isdt=0
!!iser=0
istr=1
!!itimes=0
ityp=1
!!lts0=.false.
tim_name='T1HR_PWS'
!!unt1=2
!!unt2=2
unt3=2

[namelist:umstash_use(pwsdiags_d3f31af7)]
file_id='pwspp'
locn=3
!!macrotag=0
use_name='PWSDIAGS'
