[namelist:run_bl]
cbl_op=3
local_fa=3

[namelist:run_cloud]
cff_spread_rate=1.0e-5
dbsdtbs_turb_0=1.5e-4
ez_max_bm=400.0
falliceshear_method=2
forced_cu=2
forced_cu_fac=0.5
i_cld_area=0
i_cld_vn=2
!!i_eacf=1
i_pc2_checks_cld_frac_method=2
i_pc2_conv_coupling=1
i_pc2_erosion_method=3
i_pc2_homog_g_method=1
i_pc2_init_logic=1
i_pc2_init_method=1
i_rhcpt=2
l_bm_ez_subcrit_only=.false.
l_ensure_min_in_cloud_qcf=.false.
l_micro_eros=.true.
l_pc2_check_init=.true.
l_pc2_implicit_erosion=.false.
l_pc2_lbc=.false.
l_pc2_sl_advection=.false.
l_sharpen_cbh_diags=.false.

[namelist:run_stochastic]
!!decorr_ts_pert_theta=600.0
i_pert_theta=0
!!i_pert_theta_type=0
!!l_only_pert_near_edge=.false.
!!l_pert_all_points=.false.
!!l_pert_shape=.true.
!!mag_pert_theta=0.5
!!npts_pert_from_edge=0
!!npts_pert_theta=8
!!zmax_pert_theta=400.0
!!zmin_pert_theta=0.0
