[namelist:jules_surface_types]
tile_map_ids=1,2,3,4,5,601,7,8,9
!!urban_canyon=9
!!urban_roof=10

[namelist:recon_science]
l_use_zero_frac_tile_temp=.true.

[namelist:run_murk]
l_murk=.true.
l_murk_advect=.true.
l_murk_source=.true.
l_murk_vis=.true.
m0_murk_scale=1.0
murk_source_scale=1.0

[namelist:run_precip]
!!arcl_inhom_sc=1.40
l_autoconv_murk=.true.
l_mcr_arcl=.false.

[namelist:run_radiation]
cusack_aero=3
cusack_aero_hgt=3
l_use_arclbiom=.false.
l_use_arclblck=.false.
l_use_arcldust=.false.
l_use_arclocff=.false.
l_use_arclsslt=.false.
l_use_arclsulp=.false.
l_use_biogenic=.false.

[namelist:temp_fixes]
l_fix_arcl_eg_levs=.false.
