[namelist:items(4106f9a0)]
ancilfilename='$DATADIR/ostia_seaice.anc'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=31,32
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:items(88c1d487)]
ancilfilename='$DATADIR/ostia_sst.anc'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=24
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0
