[namelist:idealised]
delta_xi1_h=0.0
delta_xi1_l=0.0
delta_xi2_h=0.0
delta_xi2_l=0.0
nxi1l=0
nxi1v=0
nxi2l=0
nxi2v=0

[namelist:model_domain]
l_regular=.false.

[namelist:nlsizes]
var_grid='$HORIZGRID'
