[namelist:nlstcall_pp(1)]
file_id='pp1'
!!filename='unset'
filename_base='$DATAM/${RUNID}a_pb%N'
l_reinit=.true.
packing=1
reinit_end=-1
reinit_start=0
reinit_step=12
reinit_unit=1
reserved_headers=0


[namelist:umstash_streq(1)]
dom_name='DIAG'
isec=0
item=24
package=''
tim_name='t1min'
use_name='USR_DIAGS'



[namelist:umstash_streq(03463_e224590c)]
dom_name='DIAG'
isec=3
item=463
package=''
tim_name='t1min'
use_name='USR_DIAGS'

[namelist:umstash_time(10min_5a5b450c)]
!!iedt=0
iend=-1
ifre=1
!!intv=0
!!ioff=0
iopt=1
!!isam=0
!!isdt=0
!!iser=0
istr=1
!!itimes=0
ityp=1
!!lts0=.false.
tim_name='t1min'
!!unt1=1
!!unt2=1
unt3=5

[namelist:umstash_time(1)]
!!iedt=0
iend=-1
ifre=1
!!intv=0
!!ioff=0
iopt=1
!!isam=0
!!isdt=0
!!iser=0
istr=1
!!itimes=0
ityp=1
!!lts0=.false.
tim_name='tsmin'
!!unt1=1
!!unt2=1
unt3=1

[namelist:umstash_use(1)]
file_id='pp1'
locn=3
!!macrotag=0
use_name='USR_DIAGS'

[namelist:umstash_streq(1)]
dom_name='DIAG'
isec=4
item=201
package=''
tim_name='t1min'
use_name='USR_DIAGS'

[namelist:umstash_streq(2)]
dom_name='DIAG'
isec=5
item=201
package=''
tim_name='t1min'
use_name='USR_DIAGS'

[namelist:umstash_streq(3)]
dom_name='DIAG'
isec=16
item=222
package=''
tim_name='t1min'
use_name='USR_DIAGS'

[namelist:umstash_streq(5)]
dom_name='DIAG'
isec=4
item=201
package=''
tim_name='tsmin'
use_name='USR_DIAGS'

[namelist:umstash_streq(6)]
dom_name='DIAG'
isec=5
item=201
package=''
tim_name='tsmin'
use_name='USR_DIAGS'

[namelist:umstash_streq(7)]
dom_name='DIAG'
isec=16
item=222
package=''
tim_name='tsmin'
use_name='USR_DIAGS'

