[namelist:items(5751f0df)]
ancilfilename='$UM_ANCIL_SOILDUST_DIR/$UM_ANCIL_SOILDUST_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=418,419,420,421,422,423,424,425,426,
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:jules_pftparm]
dust_veg_scj_io=0.0,0.0,1.0,1.0,0.5

[namelist:nlstcall_pp(dustdiags)]
file_id='dustdiags'
!!filename='unset'
filename_base='$DATAM/${RUNID}a_pdust%N'
l_reinit=.true.
packing=1
reinit_end=-1
reinit_start=0
reinit_step=6
reinit_unit=1
reserved_headers=0

[namelist:run_dust]
dust_veg_emiss=1
horiz_d=1.00
i_dust=1
l_dust_div1_lbc=.true.
l_dust_div2_lbc=.true.
l_dust_div3_lbc=.true.
l_dust_div4_lbc=.true.
l_dust_div5_lbc=.true.
l_dust_div6_lbc=.true.
l_fix_size_dist=.true.
l_twobin_dust=.false.
pwsdiag_sfc_em=0.0
sm_corr=0.30
us_am=2.20

[namelist:run_radiation]
l_use_dust=.true.

[namelist:umstash_domain(daod_1367349c)]
dom_name='DAOD'
!!iest=0
!!ilevs=0
imn=0
imsk=1
!!inth=0
iopa=1
iopl=5
!!isth=0
!!iwst=0
iwt=0
!!l_spml_ts=.false.
!!levb=0
!!levlst=0
!!levt=0
plt=4
pslist=1,2,3,4,5,6
!!rlevlst=0.0
!!spml_bot=0
!!spml_ew=0
!!spml_ns=0
!!spml_top=0
!!tblim=0
!!tblimr=0.0
!!telim=0
!!tnlim=0
ts=.false.
!!tslim=0
!!tsnum=0
!!ttlim=0
!!ttlimr=0.0
!!twlim=0

[namelist:umstash_streq(02422_19d4a8b1)]
dom_name='DAOD'
isec=2
item=422
package=''
tim_name='T1HR_0-End'
use_name='DUSTDIAGS'

[namelist:umstash_time(t1hr_0-end_abb2420e)]
!!iedt=0
iend=-1
ifre=1
!!intv=0
!!ioff=0
iopt=1
!!isam=0
!!isdt=0
!!iser=0
istr=0
!!itimes=0
ityp=1
lts0=.false.
tim_name='T1HR_0-End'
!!unt1=2
!!unt2=2
unt3=2

[namelist:umstash_use(dustdiags_76a35175)]
file_id='dustdiags'
locn=3
!!macrotag=0
use_name='DUSTDIAGS'
