[namelist:items(7b75339e)]
ancilfilename='$UM_ANCIL_OROG_DIR/$UM_ANCIL_OROG_FILE_MN'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.true.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=33
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:items(ada02aed)]
ancilfilename='$UM_ANCIL_OROG_DIR/$UM_ANCIL_OROG_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.true.
!!netcdf_varname=9*'unset'
!!period=1
source=2
stash_req=5,6,7,17,18,34,35,36,37
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0
