[namelist:jules_sea_seaice]
beta_floe=1.0
cdn_max_sea=0.0024
ce_floe=0.222
d_floe_max=300.0
d_floe_min=8.0
emis_sice=0.976
h_freeboard_max=0.534
h_freeboard_min=0.286
i_high_wind_drag=1
kappai_snow=0.256
l_iceformdrag_lupkes=.true.
l_stability_lupkes=.true.
ss_floe=0.5
!!z0h_z0m_miz=0.2
z0h_z0m_sice=0.2
!!z0miz=1.00000e-1
z0sice=5.00000e-4

[namelist:jules_snow]
graupel_options=0
i_basal_melting_opt=1

[namelist:jules_surface]
beta_cnv_bl=0.04
cor_mo_iter=4

[namelist:jules_temp_fixes]
l_fix_albsnow_ts=.true.

[namelist:run_bl]
cbl_op=3
local_fa=3

[namelist:run_cloud]
cff_spread_rate=1.0e-5
dbsdtbs_turb_0=1.5e-4
ez_max_bm=400.0
falliceshear_method=2
forced_cu=2
forced_cu_fac=0.5
i_cld_area=0
i_cld_vn=2
!!i_eacf=1
i_pc2_checks_cld_frac_method=2
i_pc2_conv_coupling=1
i_pc2_erosion_method=3
i_pc2_homog_g_method=1
i_pc2_init_logic=1
i_pc2_init_method=1
i_rhcpt=2
ice_fraction_method=3
l_bm_ez_subcrit_only=.false.
l_ensure_min_in_cloud_qcf=.false.
l_micro_eros=.true.
l_pc2_check_init=.true.
l_pc2_implicit_erosion=.false.
l_pc2_lbc=.false.
l_pc2_sl_advection=.false.
l_sharpen_cbh_diags=.false.

[namelist:run_convection]
l_jules_flux=.true.

[namelist:run_diffusion]
hyd_mix_opt=1
l_leonard_term=.true.
leonard_kl=2.0
turb_startlev_horiz=1

[namelist:run_stochastic]
!!decorr_ts_pert_theta=600.0
i_pert_theta=0
!!i_pert_theta_type=0
!!l_only_pert_near_edge=.false.
!!l_pert_all_points=.false.
!!l_pert_shape=.true.
!!mag_pert_theta=0.5
!!npts_pert_from_edge=0
!!npts_pert_theta=8
!!zmax_pert_theta=400.0
!!zmin_pert_theta=0.0
