[env]
MPICH_MPIIO_HINTS=*:striping_factor=4:striping_unit=8388608

[namelist:io_control]
io_timing=1
io_use_unique_units=.false.
print_runtime_info=.true.

[namelist:ioscntl]
ios_as_concurrency=50
ios_async_levs_per_pack=2
ios_buffer_size=11264
ios_concurrency=50
ios_concurrency_max_mem=500
ios_enable_mpiio=.true.
ios_interleave=.false.
ios_no_barrier_fileops=.false.
ios_offset=1992
ios_spacing=18
ios_tasks_per_server=24
ios_timeout=1200
ios_unit_alloc_policy=3

[namelist:prnt_control]
prnt_force_flush=.true.
