[namelist:idealised]
delta_xi1_h=0.0
delta_xi1_l=0.0
delta_xi2_h=0.0
delta_xi2_l=0.0
nxi1l=0
nxi1v=0
nxi2l=0
nxi2v=0

[namelist:items(4ec0b501)]
ancilfilename='$UM_ANCIL_GENSEA_DIR/$UM_ANCIL_GENSEA_FILE'
domain=1
!!interval=1
l_ignore_ancil_grid_check=.true.
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=96
update_anc=.false.
!!user_prog_ancil_stash_req=
!!user_prog_rconst=0.0

[namelist:items(618a18fe)]
ancilfilename='${UM_ANCIL_VEGFRAC_DIR}/${UM_ANCIL_URBAN_FILE}'
domain=1
!!interval=0
l_ignore_ancil_grid_check=.false.
!!netcdf_varname='unset','unset','unset'
!!period=1
source=2
stash_req=494,495,496
update_anc=.false.
!!user_prog_ancil_stash_req=0
!!user_prog_rconst=0

[namelist:items(b3b47f26)]
ancilfilename='${UM_ANCIL_AEROSOLS_DIR}/${UM_ANCIL_MURK_FILE}'
domain=1
!!interval=0
l_ignore_ancil_grid_check=
!!netcdf_varname='unset'
!!period=1
source=2
stash_req=57
update_anc=.false.
!!user_prog_ancil_stash_req=0
!!user_prog_rconst=0

[namelist:items(bc77512b)]
source=1

[namelist:jules_deposition_species(1)]
!!rsurf_std_io=10*-1073741824

[namelist:jules_deposition_species_specific]
!!ch4_up_flux_io=10*-1073741824
!!h2dd_c_io=10*-1073741824
!!h2dd_m_io=10*-1073741824
!!h2dd_q_io=10*-1073741824

[namelist:jules_elevate]
l_elev_absolute_height=10*.false.
surf_hgt_io=10*0.00

[namelist:jules_nvegparm]
albsnc_nvg_io=6.00000e-2,8.00000e-1,8.00000e-1,4.00000e-1,4.00000e-1
albsnf_nvg_io=6.00000e-2,-1.00000,7.50000e-1,1.80000e-1,1.80000e-1
!!albsnf_nvgl_io=0.06,0.03,0.75,0.16,0.16
!!albsnf_nvgu_io=0.15,0.80,0.75,0.20,0.20
catch_nvg_io=0.00000,0.00000,0.00000,5.00000e-1,5.00000e-1
ch_nvg_io=4.18000e+6,0.00000,0.00000,2.80000e+5,2.80000e+5
emis_nvg_io=9.85000e-1,9.00000e-1,9.90000e-1,9.70000e-1,9.70000e-1
gs_nvg_io=0.00000,1.00000e-2,1.00000e+6,0.00000,0.00000
infil_nvg_io=0.00000,5.00000e-1,0.00000,1.00000e-1,1.00000e-1
vf_nvg_io=1.00000,0.00000,0.00000,0.00000,1.00000
z0_nvg_io=1.00000e-4,1.00000e-3,5.00000e-4,1.00000,1.00000
z0hm_classic_nvg_io=1.00000e-1,1.00000e-2,1.00000e-1,1.00000e-7,1.00000e-7
z0hm_nvg_io=2.50000e-1,2.00000e-1,2.00000e-1,1.00000e-7,1.00000e-7

[namelist:jules_snow]
a_snow_et=2.8e-6
b_snow_et=0.042
c_snow_et=0.046
dzsnow=0.04,0.12,0.34
graupel_options=2
i_grain_growth_opt=1
i_relayer_opt=1
i_snow_cond_parm=1
l_et_metamorph=.true.
l_snow_infilt=.true.
l_snow_nocan_hc=.true.
nsmax=3
rho_snow_et_crit=150.0
rho_snow_fresh=170.0

[namelist:jules_surface]
all_tiles=1
l_anthrop_heat_src=.true.
l_mo_buoyancy_calc=.true.
l_urban2t=.true.

[namelist:jules_surface_types]
ice=8
lake=6
nnvg=5
soil=7
tile_map_ids=1,2,3,4,5,7,8,9,6,6
!!urban=0
urban_canyon=9
urban_roof=10

[namelist:jules_urban]
anthrop_heat_scale=1.00
l_moruses_albedo=.true.
l_moruses_emissivity=.true.
l_moruses_macdonald=.true.
l_moruses_rough=.true.
l_moruses_storage=.true.
l_moruses_storage_thin=.true.

[namelist:lam_config]
delta_lat=0.015
delta_lon=0.015

[namelist:lbc_options]
rimweightsa=5*1.000,0.750,0.500,0.250,22*0.000

[namelist:model_domain]
l_regular=.false.

[namelist:nlsizes]
var_grid='$UMDIR/vn${VN}/ctldata/horiz/horizgr_ukv_9501025_uk_um_eg'
vert_lev='$ROSE_SUITE_DIR/etc/vert_levs/L70_40km'

[namelist:recon_science]
l_adj_t_soil=.false.
l_use_zero_frac_tile_temp=.true.

[namelist:run_dyn]
solver_precision=32

[namelist:run_murk]
l_murk=.true.
l_murk_advect=.true.
l_murk_source=.true.
l_murk_vis=.true.
m0_murk_scale=2.0
murk_source_scale=1.0

[namelist:run_precip]
!!arcl_inhom_sc=1.40
l_autoconv_murk=.true.
l_mcr_arcl=.false.

[namelist:run_radiation]
cusack_aero=3
cusack_aero_hgt=3
l_use_arclbiom=.false.
l_use_arclblck=.false.
l_use_arcldust=.false.
l_use_arclocff=.false.
l_use_arclsslt=.false.
l_use_arclsulp=.false.
l_use_biogenic=.false.

[namelist:temp_fixes]
l_fix_arcl_eg_levs=.false.
l_fix_riming=.false.
