[namelist:jules_sea_seaice]
beta_floe=1.0
cdn_max_sea=0.0024
ce_floe=0.222
d_floe_max=300.0
d_floe_min=8.0
emis_sice=0.976
h_freeboard_max=0.534
h_freeboard_min=0.286
i_high_wind_drag=1
kappai_snow=0.256
l_iceformdrag_lupkes=.true.
l_stability_lupkes=.true.
ss_floe=0.5
!!z0h_z0m_miz=0.2
z0h_z0m_sice=0.2
!!z0miz=1.00000e-1
z0sice=5.00000e-4

[namelist:jules_snow]
graupel_options=0
i_basal_melting_opt=1

[namelist:jules_surface]
beta_cnv_bl=0.04
cor_mo_iter=4

[namelist:jules_temp_fixes]
l_fix_albsnow_ts=.true.

[namelist:run_cloud]
i_eacf=2
ice_fraction_method=3

[namelist:run_convection]
l_jules_flux=.true.

[namelist:run_diffusion]
hyd_mix_opt=1
l_leonard_term=.true.
leonard_kl=2.0
turb_startlev_horiz=1
