[env]
DATAM=$DATADIR
DATAW=$DATADIR
HISTORY=$DATADIR/umnsa.xhist

[namelist:lam_config]
polelata=$POLE_LAT
polelona=$POLE_LON

[namelist:lbc_options]
nrim_timesa=$NLBC_TIMES

[namelist:nlcfiles]
alabcin1='$ALABCIN1'
astart='$ASTART'

[namelist:nlsizes]
bl_levels=$NLEVSM1
cloud_levels=$NLEVS
global_row_length=$NPTS_X
global_rows=$NPTS_Y
model_levels=$NLEVS
ozone_levels=$NLEVS
vert_lev='$VERT_LEV'

[namelist:nlstcall]
run_target_end=$RUN_END

[namelist:nlstcgen]
dumpfreqim=$CRUN_LEN
steps_per_periodim=$NTSTEPS

[namelist:recon_technical]
ainitial='$AINITIAL'

[namelist:run_cloud]
rhcrit=$RHCRIT

[namelist:run_diffusion]
norm_lev_end=$NLEVS
turb_endlev_horiz=$NLEVSM1
turb_endlev_vert=$NLEVSM1

[namelist:run_dyn]
!!damp_height=40000.0

[namelist:run_precip]
l_mcr_qrain_lbc=$LBC_RAIN

[namelist:run_radiation]
aero_bl_levels=$AERO_BL_LEVS
i_lw_radstep_perday_diag=$RADSTEP_DIAG
i_lw_radstep_perday_prog=$RADSTEP_PROG
i_sw_radstep_perday_diag=$RADSTEP_DIAG
i_sw_radstep_perday_prog=$RADSTEP_PROG

[namelist:temp_fixes]
l_eg_damp_height_lid=.true.
