[prune]
prune{share/cycle}=$HK_CYCLE:'*/*/*_cb*'
                  =-PT0H:'*/*/*_da* */*/*_astart */*/*_atmanl */*/*.stash */*/*.xhist'
                  =$HK_CYCLE:'*/*/*/*/*_da*'
                  =-PT0H:'*/*/*/*/*_cb* */*/*/*/*_astart */*/*/*/*_atmanl */*/*/*/*_frame_* */*/*/*/*_alabc_* */*/*/*/*.anc */*/*/*/*.stash */*/*/*/*.xhist'
