[command]
default=/bin/true

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=/home/moum/UM/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=/home/moum/UM/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_SUITE_DIR/share/fcm_make]
mode=symlink
source=/home/jkumar/vn11.X/fcm_make
###commented for the new ancil data 
#[file:$ROSE_SUITE_DIR/share/data]
#mode=symlink
#source=/home/jkumar/vn11.X/data

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
#source= /home/moum/UM/vn11.X/xc40/utilities
source=/home/shivali/cylc-run/UM_11.1_r56263/share/fcm_make_meto_xc40_cce_createbc_high_omp/build-createbc/bin

[file:$ROSE_SUITE_DIR/share/fcm_make_pptoanc]
mode=symlink
source=/home/moum/UM/vn11.X/xc40/utilities

#
# Global model settings below were previously set in their own file.
#
[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=/home/moum/UM/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
###source=/gpfs2/home/umtid/UM/vn${UM_VN}/ctldata/spectral/ga7
source=/home/moum/UM/vn${UM_VN}/ctldata/spectral/ga7
#
# S WEBSTER comment 7th July 2017. Shouldn't the above end ga7 rather than ga7_0
#
# Needed for RA1 ticket #9. Once suite at vn10.8, this
# symlink can revert to the one above.
#
[file:$ROSE_DATA/etc/um_spectral_ga7_108]
mode=symlink
source=/home/moum/UM/vn10.8/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6]
mode=symlink
source=/home/moum/UM/ancil/data/ancil_versions/${GLM_RESLN}e/ps39/v2/ancils
#source=/home/moum/UM/ancil/data/ancil_versions/${GLM_RESLN}e/GA6.0/v2/ancils
###
##source=/gpfs1/home/moum/UM/ancil/data/ancil_versions/${GLM_RESLN}e/ps34/v4/ancils
###

[file:$ROSE_DATA/etc/ancil_versions_ga7]
mode=symlink
#
# S Swebster comment 14/12/16
# Link beloe needs to point at GA7 ancillaries
#
#source=/home/moum/UM/ancil/data/ancil_versions/${GLM_RESLN}e/GA7.0/v2/ancils
source=/home/moum/UM/ancil/data/ancil_versions/${GLM_RESLN}e/ps41/latest/ancils
