[command]
default=moo mkset --single-copy -p project-${CHARGING_CODE} moose:/devfc/$ARCHIVE_SET_NAME || true

[file:$ROSE_DATA/etc/ants_lsm_vegfrac_nc]
# location of preprocessed vegfrac and lsm netcdf files
mode=symlink
source=/work/n02/n02/grenvill/transforms

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=/work/y07/shared/umshared/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=/work/y07/shared/umshared/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_DATA/etc/ancil_master]
mode=symlink
source=/work/y07/shared/umshared/ancil/atmos/master

#
# This is the full path to the directory containing the L90 aerosol ancillaries.
#
[file:$ROSE_DATA/etc/ancil_master_aero]
mode=symlink
source=/projects/cascade/hadsw/NS/RA2_AERO_ANCILS/aero_clims/GA6.0_antie/L90_40km_20YR/v2

# Soure of aero ancils for ANTS
[file:$ROSE_DATA/etc/ancil_master_aero_ants]
mode=symlink
source=/work/y07/shared/umshared/ancil/atmos/master

[file:$ROSE_DATA/etc/ancil_atmos]
mode=symlink
source=/work/y07/shared/umshared/ancil/atmos

[file:$ROSE_DATA/etc/ancil_parms]
mode=symlink
source=/work/y07/shared/umshared/ancil/data/parameters

[file:$ROSE_SUITE_DIR/share/fcm_make_cap]
mode=symlink
source=/work/y07/shared/umshared/CAP9.1/build/bin

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
source=/work/y07/shared/umshared/vn${UM_VN}/cce/utilities

[file:$ROSE_SUITE_DIR/share/fcm_make_surf]
mode=symlink
source=/work/y07/shared/umshared/SURF/surf-2020.01.2/fcm_make_surf_archer2_ftn_opt

#
# global ancil settings below. Previously these were in their own file.
#
[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=/work/y07/shared/umshared/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
source=/work/y07/shared/umshared/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6p1]
mode=symlink
source= /work/y07/shared/umshared/ancil/data/ancil_versions/${GLM_RESLN}e/GA6.0/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga6p1_gl8p1]
mode=symlink
source=/work/y07/shared/umshared/ancil/data/ancil_versions/${GLM_RESLN}e/ps41/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga7p2_gl8p1]
mode=symlink
source=/work/y07/shared/umshared/ancil/data/ancil_versions/${GLM_RESLN}e/ps43/latest/ancils

#
# This is the full path to the directory containing the netcdf ukca ancillary data for
# offline oxidants and emmissions. The standard setup uses CMIP5 emissions.
#
[file:$ROSE_DATA/etc/ancil_ukca_aero]
mode=symlink
source=/projects/asci/hadzm/ancils/n512e_mon_gcal/ncdf_ukca

[file:$ROSE_DATA/etc/ancil_ukca_glm1]
mode=symlink
source=/projects/ukca-leeds/hamgo/ancils/ukca-v10p3/n216e_mon_gcal/ncdf_ukca

[file:$ROSE_DATA/etc/ancil_ukca_glm2]
mode=symlink
source=/work/y07/shared/umshared/ancil/atmos/${GLM_RESLN}e/
