[command]
default=/bin/true

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=/oper/admin/um_fcm/um/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=/oper/admin/um_fcm/um/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
source=/oper/admin/um_fcm/um/vn${UM_VN}/ibm/utilities/

#
# Global model settings previously set in their own file.
#

[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=/oper/admin/um_fcm/um/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
source=/oper/admin/um_fcm/um/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6]
mode=symlink
source=/oper/admin/um_fcm/um/ancils/${GLM_RESLN}L70e-ancils/ancil_versions

[file:$ROSE_DATA/etc/ancil_versions_ga7]
mode=symlink
#
# S Webster comment added 14/12/16
# Need to update link below to plint at GA7 ancillaries
#
source=/oper/admin/um_fcm/um/ancils/${GLM_RESLN}L70e-ancils/ancil_versions
