[command]
default=/opt/freeware/bin/true

[env]
ANCILHOME = /home/users/um/ancil
UMHOME = /home/users/um

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=$UMHOME/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=$UMHOME/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_DATA/etc/ancil_atmos]
mode=symlink
source=$ANCILHOME/ancil/atmos

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
source=$UMHOME/cylc-run/um10.6-boreasz-utils/share/fcm_make_utils

#
# Global model settings previously set in their own file.
#

[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=$UMHOME/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
source=$UMHOME/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6]
mode=symlink
source=$ANCILHOME/data/ancil_versions/${GLM_RESLN}e/GA6.0/latest/ancils
