[command]
default=

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
source=$UMDIR/vn${UM_VN}/xc30/utilities

#
# Global model settings previously set in their own file.
#
[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6]
mode=symlink
source=$UMDIR/ancil/data/ancil_versions/${GLM_RESLN}e/ps36/v5/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga7]
mode=symlink
#
# S Webster comment added 14/12/16
# Need to point link below at GA7 ancillaries. 
#
source=$UMDIR/ancil/data/ancil_versions/${GLM_RESLN}e/ps36/v5/ancils
