[command]
default=moo mkset moose:/devfc/$ARCHIVE_SET_NAME || true

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=/s4/home/nwpr/gum/UMSD/prebuild/UM/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
#source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/vn10.1/DABA/ctldata/spectral/ga3_1
source=/s4/home/nwpr/gum/UMSD/prebuild/UM/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_DATA/etc/ancil_atmos]
mode=symlink
#source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/ancil/atmos
source=/op/nwp/fcst/MODL/GDPS/N768/DABA/ancil/atmos

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
#source=/s4/home/nwpr/lhy3189/cylc-run/vn10.4_update_kma_site_to_rose_stem/share/fcm_make_kma_xc40_cce_um_debug_noomp/extract/um/bin
#source=/s4/home/nwpr/gum/UMSD/prebuild/UM/vn10.4/xc40/utilities
source=/s4/home/nwpr/lhy3189/UMSD/prebuild/UM/vn${UM_VN}/xc40/utilities

[file:$ROSE_SUITE_DIR/share/fcm_make_surf]
mode=symlink
source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/vn10.1/builds/fcm_make_surf/build/bin

#
# global model directories below. Previously in their own file.
#
[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
#source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/vn10.1/DABA/ctldata/spectral/ga3_0
source=/s4/home/nwpr/gum/UMSD/prebuild/UM/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
#source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/vn10.1/DABA/ctldata/spectral/ga3_0
source=/s4/home/nwpr/gum/UMSD/prebuild/UM/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6]
mode=symlink
#source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/ancil/data/ancil_versions/${GLM_RESLN}e/GA6.0
source=/op/nwp/fcst/MODL/GDPS/N768/DABA/ancil/data/ancil_versions/n768e/ps36/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga7]
mode=symlink
#source=/s4/home/nwpr/lhy250/UMSD/prebuild/UM/ancil/data/ancil_versions/${GLM_RESLN}e/GA6.0
#
# S Swebster comment 14/12/16
# The link needs updating to point at the GA7 ancillaries.
#
source=/op/nwp/fcst/MODL/GDPS/N768/DABA/ancil/data/ancil_versions/n768e/ps36/latest/ancils
