[command]
default=moo mkset --single-copy -p project-${CHARGING_CODE} moose:/devfc/$ARCHIVE_SET_NAME || true

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=/projects/um1/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=/projects/um1/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_DATA/etc/ancil_atmos]
mode=symlink
source=/projects/um1/ancil/atmos

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
source=/projects/um1/vn${UM_VN}/xc40/utilities

[file:$ROSE_SUITE_DIR/share/fcm_make_surf]
mode=symlink
source=~hadsw/ROSE_NS/fcm_make_surf_xc40_haswell_ifort_opt

#
# global ancil settings below. Previously these were in their own file.
#
[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=/projects/um1/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
source=/projects/um1/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/um_spectral_ga7_1]
mode=symlink
source=/projects/um1/vn${UM_VN}/ctldata/spectral/ga7_1

[file:$ROSE_DATA/etc/ancil_versions_ga6p1]
mode=symlink
source= /projects/um1/ancil/data/ancil_versions/${GLM_RESLN}e/GA6.0/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga6p1_gl8p1]
mode=symlink
source=/projects/um1/ancil/data/ancil_versions/${GLM_RESLN}e/ps41/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga7p2_gl8p1]
mode=symlink
source=/projects/um1/ancil/data/ancil_versions/${GLM_RESLN}e/ps43/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga8_gl9]
mode=symlink
source=/projects/um1/ancil/data/ancil_versions/${GLM_RESLN}e_orca025/ps45/v1/ancils

[file:$ROSE_DATA/etc/ancil_versions_CoMorphA]
mode=symlink
source=/projects/um1/ancil/data/ancil_versions/${GLM_RESLN}e_orca025/ps45/v1/ancils

[file:$ROSE_DATA/etc/ancil_versions_CoMorphA9]
mode=symlink
source=$UMDIR/ancil/data/ancil_versions/${GLM_RESLN}e_orca025/ps45/v1/ancils

#
# This is the full path to the directory containing the netcdf ukca ancillary data for
# offline oxidants and emmissions. The standard setup uses CMIP5 emissions.
#
[file:$ROSE_DATA/etc/ancil_ukca_glm1]
mode=symlink
source=/projects/ukca-leeds/hamgo/ancils/ukca-v10p3/n216e_mon_gcal/ncdf_ukca

[file:$ROSE_DATA/etc/ancil_ukca_glm2]
mode=symlink
source=/projects/um1/ancil/atmos/${GLM_RESLN}e/
