[env]
CAP_VN=9.1

[command]
default=

[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/um_spectral_lam]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/spectral/ga3_1

[file:$ROSE_DATA/etc/ancil_atmos]
mode=symlink
source=$UMDIR/ancil/atmos

[file:$ROSE_SUITE_DIR/share/fcm_make_um_utils]
mode=symlink
source=$UMDIR/vn${UM_VN}/linux/utilities

[file:$ROSE_SUITE_DIR/share/fcm_make_surf]
mode=symlink
source=/h/GALWEM/surf

#
# global model directories below. Previously in their own file.
#
[file:$ROSE_DATA/etc/um_spectral_ga6]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/spectral/ga3_0

[file:$ROSE_DATA/etc/um_spectral_ga7]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/spectral/ga7

[file:$ROSE_DATA/etc/ancil_versions_ga6]
mode=symlink
source=$UMDIR/ancil/data/ancil_versions/${GLM_RESLN}e/GA6.0/latest/ancils

[file:$ROSE_DATA/etc/ancil_versions_ga7]
mode=symlink
source=$UMDIR/ancil/data/ancil_versions/${GLM_RESLN}e/GA7.0/latest/ancils
